#!/usr/bin/env ansible-playbook
---
- name: Start up an alpine containertools image
  hosts: localhost


  tasks:
    - name: Start up a docker container
      docker_container:
        name: client
        image: raesene/alpine-containertools
    - name: add the host
      add_host: name=client

- name: install Python in the cluster
  hosts: client
  connection: docker
  gather_facts: no

  tasks:
  - import_tasks: ./ansible_tasks/install_python3_alpine_raw.yml
  
- name: Configure the demo client
  hosts: client
  connection: docker

  tasks:
  - name: Set the bash prompt
    copy:
      src: client_files/clientbashrc
      dest: /root/.bashrc