#!/usr/bin/env ansible-playbook
---
- name: Start up a kind cluster
  hosts: localhost
  vars:
    cluster_name: sshcm
    # This needs to be the cluster name with -control-plane added 
    container_name: sshcm-control-plane

  tasks:
  - import_tasks: ./ansible_tasks/setup_kind_standard_config.yaml
  # This needs to be in place for every playbook using kind as we need Python
- name: install Python in the cluster
  hosts: sshcm-control-plane
  connection: docker
  gather_facts: no

  tasks:
  - import_tasks: ./ansible_tasks/install_python3_raw.yml
  

- name: Setup Cluster
  hosts: sshcm-control-plane
  connection: docker

  tasks:
  - import_tasks: ./ansible_tasks/setup_kubeconfig.yml
  - import_tasks: ./ansible_tasks/setup_ssh_pod.yml
  - import_tasks: ./ansible_tasks/make_default_service_account_cluster_admin.yaml 
  - import_tasks: ./ansible_tasks/print_cluster_ip.yml