#!/usr/bin/env ansible-playbook
---
- name: Start up a kind cluster
  hosts: localhost
  vars:
    cluster_name: testcluster
    container_name: testcluster-control-plane

  tasks:
   - import_tasks: ./ansible_tasks/setup_kind_standard_config.yaml

- name: install Python in the cluster
  hosts: testcluster-control-plane
  connection: docker
  gather_facts: no

  tasks:
  - import_tasks: ./ansible_tasks/install_python3_raw.yml
  

- name: test something in the cluster
  hosts: test-control-plane
  connection: docker

  tasks:
    - name: add nmap
      apt:
        name: ['nmap']
        state: present
