#!/usr/bin/env ansible-playbook
---
- name: Start up a kind cluster
  hosts: localhost
  vars:
    cluster_name: testcluster
    container_name: testcluster-control-plane
    kubernetes_version: v1.18.2

  tasks:
   - import_tasks: ./ansible_tasks/setup_kind_standard_config.yaml

- name: test something in the cluster
  hosts: test-control-plane
  connection: docker

  tasks:
    - name: add nmap
      apt:
        name: ['nmap']
        state: present
